packages:
  - packages/libs/*
  - packages/apps/*
  - packages/external/*

catalog:
  '@douyinfe/semi-icons': ^2.90.0
  '@douyinfe/semi-illustrations': ^2.90.0
  '@douyinfe/semi-ui': ^2.90.0
  '@eslint/js': ^9.39.2
  '@react-three/drei': ^9.115.0
  '@react-three/fiber': ^8.17.10
  '@react-three/uikit': ^0.8.3
  '@stylistic/eslint-plugin': ^5.6.1
  '@types/lodash-es': ^4.17.12
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/react-reconciler': ^0.28.8
  '@types/serviceworker': ^0.0.172
  '@types/three': ^0.170.0
  '@types/wicg-file-system-access': ^2023.10.7
  '@vitejs/plugin-react': ^5.1.2
  dexie: ^4.2.1
  es-toolkit: ^1.43.0
  eslint: ^9.39.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-hooks-better-stable: ^1.0.4
  eslint-plugin-react-refresh: ^0.4.26
  fast-check: 4.5.2
  filesize: ^10.1.6
  globals: ^16.5.0
  lodash-es: ^4.17.22
  memfs: ^4.51.1
  mime: ^4.1.0
  monaco-editor: ^0.52.0
  monaco-editor-textmate: ^4.0.0
  monaco-textmate: ^3.0.1
  onigasm: ^2.2.5
  quickjs-emscripten: ^0.31.0
  r3f-perf: ^7.2.3
  react: ^19.2.3
  react-dom: ^19.2.3
  react-query: ^3.39.3
  react-reconciler: ^0.29.2
  sharp: ^0.34.5
  three: ^0.170.0
  ts-pattern: ^5.9.0
  typescript: ^5.9.3
  typescript-eslint: ^8.50.1
  typescript-plugin-css-modules: ^5.2.0
  universal-router: ^10.0.1
  vite: ^7.3.0
  vite-bundle-analyzer: ^1.3.2
  vite-plugin-node-polyfills: ^0.24.0
  vite-plugin-svgr: ^4.5.0
  vitest: ^4.0.16
  zod: ^4.2.1
