packages:
  # 基础包
  - "packages/libs/*"
  # 应用
  - "packages/apps/*"
  # 外部包
  - "packages/external/*"

catalog:
  "@douyinfe/semi-icons": "^2.68.4"
  "@douyinfe/semi-illustrations": "^2.68.4"
  "@douyinfe/semi-ui": "^2.68.4"
  "dexie": "^4.0.9"
  "filesize": "^10.1.6"
  "lodash-es": "^4.17.21"
  "memfs": "^4.14.0"
  "mime": "^4.0.4"
  "monaco-editor": "^0.52.0"
  "monaco-editor-textmate": "^4.0.0"
  "monaco-textmate": "^3.0.1"
  "onigasm": "^2.2.5"
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "react-query": "^3.39.3"
  "ts-pattern": "^5.5.0"
  "typescript": "^5.6.3"
  "universal-router": "^9.2.0"

  "@types/lodash-es": "^4.17.12"
  "@types/node": "^22.9.0"
  "@types/react": "^18.3.12"
  "@types/react-dom": "^18.3.1"
  "@types/serviceworker": "^0.0.101"
  "@types/wicg-file-system-access": "^2023.10.5"
